package by.epamtc.jwd2020.dziadkouskaya.controller.command;

public enum ParametrName {

	GO_TO_CONTACTS,
	GO_TO_FIRST_PAGE, 
	GO_TO_REGISTRATION_PAGE, 
	GO_TO_LOGINATION_PAGE, 
	USER_REGISTRATION,
	WELCOME_NEW_USER,
	USER_LOGINATION, 
	UPDATE_USER_DETAILS,
	UPDATE_USER,
	UPDATE_SECURITY,
	DELETE_USER,
	USER_WAS_DELETED,
	BOOKING_PAGE,
	RESULT_BOOKING_LIST,
	BOOKING_DETAILS,
	BOOKING_HISTORY,
	EXIT_TO_MAIN_PAGE,
	NEW_ROOM_BOOKING,
	PREPAIMENT_PAID,
	ADMIN_USER_BOOKING,
	ADMIN_CHECK_IN_CLIENT,
	ADMIN_ADD_NEW_CLIENT,
	ADMIN_CLIENT_BOOKING_LIST,
	ADMIN_CLIENT_NEW_BOOKING,
	ADMIN_GO_TO_ADDING_NEW_CLIENT,
	ADMIN_WELCOME_NEW_CLIENT,
	ADMIN_GO_TO_CLIENT_PERSONAL_PAGE,
	UPDATE_CLIENT_DETAIL_WITHOUT_BOOKING,
	UPDATE_CLIENT_DETAILS,
	ADMIN_FIND_USER_TO_CHECK_IN,
	ADMIN_CHECK_IN_PAYMENT,
	ADMIN_GO_TO_ADDING_NEW_GUESTS, 
	ADMIN_ADD_NEW_GUEST,
	ADMIN_CLIENT_WAS_CHECKED_IN,
	ADMIN_CHECK_OUT_LIST,
	ADMIN_CHECK_OUT_LIST_WITH_DATE,
	ADMIN_CHECK_OUT_CLIENT_FINAL,
	ADMIN_CLEANER_LIST,
	ADMIN_GO_TO_PRICES,
	ADMIN_PRICES_DELETE, 
	ADMIN_PRICES_ADD,
	ADMIN_PRICE_GO_TO_ADDING_PAGE,
	LOCALE_CHANGE,
	ERROR_PAGE

	


}
